<?php


namespace App\models;


use App\core\Olivine;
use App\core\Response;


abstract class Model extends Olivine
{

    public string $error_validation_message;

    /**
     * Model constructor.
     * @param string $table
     */
    public function __construct(string $table)
    {
        parent::__construct($table);
    }

    /**
     * @return false|string
     */
    public function validation_error_response()
    {
        return Response::json_response_error($this->error_validation_message, 'failed', 400);
    }

    /**
     * @param array $filter
     * @param string $columns
     * @return array
     */
    public static function find(array $filter = [], $columns = '*')
    {
        return parent::find($filter, $columns); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $param
     * @param string $columns
     * @return mixed
     */
    public static function findOne(array $param, string $columns = '')
    {
        return parent::findOne($param, $columns); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $limit
     * @param int $page
     * @param array $filter
     * @param string $columns
     * @return array
     */
    public static function paginate(int $limit, int $page = 1, $filter = [], string $columns = '*')
    {
        return parent::paginate($limit, $page, $filter, $columns); // TODO: Change the autogenerated stub
    }

    /**
     * @return int
     */
    public static function rowCount()
    {
        return parent::rowCount(); // TODO: Change the autogenerated stub
    }

  public static function leftJoin(string $jointTable)
  {
    return parent::leftJoin($jointTable); // TODO: Change the autogenerated stub
  }


}